server:
  port: 8086

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:batchdb

  application:
    name: payment-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
